version: "2"

formatters:
  enable:
    - gofmt
    - gofumpt
    - golines

  settings:
    golines:
      max-len: 100
      shorten-comments: true
      reformat-tags: true

  exclusions:
    paths:
      - gioui/